name: 'Webpage - Default'
description: 'A recipe to manage default installed modules, configs and permissions.'
type: install
install:
  - node
  - path
  - text
  - user
  - block
  - block_content
  - field
  - content_moderation
  - workflows
  - menu_ui
  - pathauto
  - field_group
  - smart_trim
  - display_builder
  - display_builder_entity_view
config:
  strict:
    - field.storage.node.body
  import:
    display_builder:
      - display_builder.profile.default
